<a href="https://colab.research.google.com/github/Redcoder815/Machine_Learning_Project/blob/main/HeartDisease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [106]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [107]:
heart_data = pd.read_csv('/content/heart_disease_data.csv')

In [108]:
heart_data.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [109]:
heart_data.tail()

     age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[5 rows x 14 columns]

In [110]:
heart_data.describe()

              age         sex          cp  ...          ca        thal      target
count  303.000000  303.000000  303.000000  ...  303.000000  303.000000  303.000000
mean    54.366337    0.683168    0.966997  ...    0.729373    2.313531    0.544554
std      9.082101    0.466011    1.032052  ...    1.022606    0.612277    0.498835
min     29.000000    0.000000    0.000000  ...    0.000000    0.000000    0.000000
25%     47.500000    0.000000    0.000000  ...    0.000000    2.000000    0.000000
50%     55.000000    1.000000    1.000000  ...    0.000000    2.000000    1.000000
75%     61.000000    1.000000    2.000000  ...    1.000000    3.000000    1.000000
max     77.000000    1.000000    3.000000  ...    4.000000    3.000000    1.000000

[8 rows x 14 columns]

In [111]:
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [112]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [113]:
heart_data['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [114]:
X = heart_data.drop(columns = 'target', axis = 1)
Y = heart_data['target']

In [115]:
print(X)
print(Y)

     age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
0     63    1   3       145   233  ...      0      2.3      0   0     1
1     37    1   2       130   250  ...      0      3.5      0   0     2
2     41    0   1       130   204  ...      0      1.4      2   0     2
3     56    1   1       120   236  ...      0      0.8      2   0     2
4     57    0   0       120   354  ...      1      0.6      2   0     2
..   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
298   57    0   0       140   241  ...      1      0.2      1   0     3
299   45    1   3       110   264  ...      0      1.2      1   0     3
300   68    1   0       144   193  ...      0      3.4      1   2     3
301   57    1   0       130   131  ...      1      1.2      1   1     3
302   57    0   1       130   236  ...      0      0.0      1   1     2

[303 rows x 13 columns]
0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [116]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [117]:
print(X.shape, X_train.shape, X_test.shape)

(303, 13) (242, 13) (61, 13)

In [118]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [119]:
class LogisticRegression:
    def __init__(self, lr=0.01, iterations=1000):
        self.lr = lr
        self.iterations = iterations
        self.weights = None
        self.bias = 0
        self.costs = []

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        # import ipdb
        # ipdb.set_trace()
        for _ in range(self.iterations):
            # 1. Forward Pass
            model_linear = np.dot(X, self.weights) + self.bias
            predictions = self.sigmoid(model_linear)

            # 2. Compute Cost (Log Loss)
            cost = - (1/n_samples) * np.sum(y * np.log(predictions + 1e-9) + (1-y) * np.log(1-predictions + 1e-9))
            self.costs.append(cost)

            # 3. Backward Pass (Gradients)
            dw = (1/n_samples) * np.dot(X.T, (predictions - y))
            db = (1/n_samples) * np.sum(predictions - y)

            # 4. Update Parameters
            self.weights -= self.lr * dw
            self.bias -= self.lr * db

    def predict(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        y_predicted = self.sigmoid(linear_model)
        return [1 if i > 0.5 else 0 for i in y_predicted]

    def accuracy(self, pred, y_true):
        pred_np = np.array(pred)
        y_true_np = y_true.to_numpy()
        correct_predictions = np.sum(pred_np == y_true_np)
        total_predictions = len(y_true_np)
        return correct_predictions / total_predictions

In [120]:
logisticModel = LogisticRegression()

In [121]:
logisticModel.fit(X_train_scaled, Y_train)

In [122]:
X_train_prediction = logisticModel.predict(X_train_scaled)
X_train_accuracy = logisticModel.accuracy(X_train_prediction, Y_train)

print('Train accuracy ', X_train_accuracy)

Train accuracy  0.8512396694214877

In [123]:
X_test_prediction = logisticModel.predict(X_test_scaled)
X_test_accuracy = logisticModel.accuracy(X_test_prediction, Y_test)

print('Test accuracy ',X_test_accuracy)

Test accuracy  0.8852459016393442

In [127]:
# input_data = (61,1,3,134,234,0,1,145,0,2.6,1,2,2)
input_data = (63,1,3,145,233,1,0,150,0,2.3,0,0,1)
input_data_as_array = np.asarray(input_data)

data_reshaped = input_data_as_array.reshape(1,-1)

# Scale the input data
scaled_input_data = scaler.transform(data_reshaped)

prediction = logisticModel.predict(scaled_input_data)
print(prediction)

if (prediction[0] == 1):
  print('The person has heart disease')
else:
  print('No heart disease')

[1]
The person has heart disease

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(